MMkit: MMkit Class Reference
MMkit Class Reference
Classes
struct cell
Public Member Functions
MMkit (AccelStepper leftMotor, AccelStepper rightMotor)
void goForward (float cm)
Description: The robot will try to move in its forward direction at the predefined.
void rotate (float deg)
Description: The robot will try to rotate over is axis positive right, negative values left.
void rotateRight (float deg)
!Description: The robot shall rotate in it's axis the specified angle to the Right.
void rotateLeft (float deg)
Description: The robot shall rotate in it's axis the specified angle to the Right.
void setupMMkit ()
Description: Perform initial configuration.
void run ()
Description: This function makes the motor do a step so must be call each time we want the motor to turn 1,8 degrees.
void stop ()
Description: This function makes the motor to stop, break.
void setIR_LEFT (float LeftCorrection)
Description: This function Set the value of the LEFT IR sensor to the wall(default is 555.
void setIR_RIGHT (float RightCorrection)
Description: This function Set the value of the Right IR sensor to the wall(default is 555.
void waitForStart ()
Description: Continuously checks for the start signal (hand movement close to the left forward distance sensor where a sequence of high, low and high distances are detected)
boolean running ()
!Description: Checks if the dstance has been reached, if so returns false else is still moving returns true
void readIRSensors ()
Description: Reads the values of the IRsensorsValues and stores the values in IRsensorsValues[0], IRsensorsValues[1], IRsensorsValues[2], IRsensorsValues[3].
void testIRSensors ()
Description: Reads the values of the IRsensorsValues and stores the values in IRsensorsValues[0], IRsensorsValues[1], IRsensorsValues[2], IRsensorsValues[3].
boolean isWallRight (void)
Description: compares de treshold value to the readvalue and if this Value is Higher returns true.
boolean isWallLeft (void)
Description: compares de treshold value to the readvalue and if this Value is Higher returns true.
boolean isWallFront (void)
Description: compares de treshold value to the readvalue and if this Value is Higher returns true.
void setForwardMotionSpeed (float speed)
void setWHEEL_SPACING(float WHEEL_SPACING);
float getForwardMotionSpeed (void)
Description: Get the configured forward motion velocity of the robot.
void setForwardMotionAcceleration (float Acceleration)
Description: Define the forward motion acceleration of the robot.
float getForwardMotionAcceleration (void)
Description: Get the configured forward motion acceleration of the robot.
void setMaxSpeeds (float leftMaxSpeed, float rightMaxSpeed)
void runSpeed ()
void runSpeedWalls (float cm)
void runSpeedRwall (float cm)
void runSpeedLwall (float cm)
Public Attributes
int IRsensorsValues [4]
boolean Correction_ON
boolean Front_Detection_ON
struct cell current_cell
struct cell track [156]
Member Function Documentation
float MMkit::getForwardMotionAcceleration (void)
Description: Get the configured forward motion acceleration of the robot.
Input parameter: none Output parameter: acceleration in cm/s
float MMkit::getForwardMotionSpeed (void)
Description: Get the configured forward motion velocity of the robot.
Input parameter: none Output parameter: speed in cm/s
void MMkit::goForward (float cm)
Description: The robot will try to move in its forward direction at the predefined.
forward motion speed. If a front wall is detected, the robot shall rotate right or left. If walls are sensed on its left and right, it shall move parallel to them and in their middle. If only one wall is sensed, it shall move parallel to it. Input parameter: none Output parameter: none
boolean MMkit::isWallFront (void)
Description: compares de treshold value to the readvalue and if this Value is Higher returns true.
Input parameter: none Output parameter: True if there is wall present
Referenced by stop().
boolean MMkit::isWallLeft (void)
Description: compares de treshold value to the readvalue and if this Value is Higher returns true.
Input parameter: none Output parameter: True if there is wall present
Referenced by stop().
boolean MMkit::isWallRight (void)
Description: compares de treshold value to the readvalue and if this Value is Higher returns true.
Input parameter: none Output parameter: True if there is wall present
Referenced by stop().
void MMkit::readIRSensors ()
Description: Reads the values of the IRsensorsValues and stores the values in IRsensorsValues[0], IRsensorsValues[1], IRsensorsValues[2], IRsensorsValues[3].
Input parameter: none Output parameter: none, values are stored at IRsensorsValues[],
Referenced by stop(), and waitForStart().
void MMkit::rotate (float deg)
Description: The robot will try to rotate over is axis positive right, negative values left.
Input parameter: desired angle in degrees Output parameter: none
void MMkit::rotateLeft (float deg)
Description: The robot shall rotate in it's axis the specified angle to the Right.
Input parameter: desired angle in degrees Output parameter: none
void MMkit::rotateRight (float deg)
!Description: The robot shall rotate in it's axis the specified angle to the Right.
Input parameter: desired angle in degrees Output parameter: none
void MMkit::run ()
Description: This function makes the motor do a step so must be call each time we want the motor to turn 1,8 degrees.
Input parameter: none Output parameter: none
boolean MMkit::running ()
!Description: Checks if the dstance has been reached, if so returns false else is still moving returns true
Input parameter: none Output parameter: True -> moving False -> Stop
Referenced by stop().
void MMkit::setForwardMotionAcceleration (float Acceleration)
Description: Define the forward motion acceleration of the robot.
Input parameter: desired acceleration in cm/s Output parameter: none
void MMkit::setForwardMotionSpeed (float speed)
void setWHEEL_SPACING(float WHEEL_SPACING);
Description: Define the Wheel Spacing of the robot Input parameter: Wheel Spacing in cm/s Output parameter: noneDescription: Define the Wheel Spacing of the robot Input parameter: Wheel Spacing in cm/s Output parameter: none void setWHEEL_RADIUS(float WHEEL_RADIUS); Description: Define the forward motion velocity of the robot Input parameter: desired speed in cm/s Output parameter: none Used by:
void MMkit::setIR_LEFT (float LeftCorrection)
Description: This function Set the value of the LEFT IR sensor to the wall(default is 555.
Input parameter: Value of IR_LEFT to the wall Output parameter: none
void MMkit::setIR_RIGHT (float RightCorrection)
Description: This function Set the value of the Right IR sensor to the wall(default is 555.
Input parameter: Value of IR_RIGHT to the wall Output parameter: none
void MMkit::setupMMkit ()
Description: Perform initial configuration.
Input parameter: none Output parameter: none
void MMkit::stop ()
Description: This function makes the motor to stop, break.
Input parameter: none Output parameter: none
References isWallFront(), isWallLeft(), isWallRight(), readIRSensors(), and running().
void MMkit::testIRSensors ()
Description: Reads the values of the IRsensorsValues and stores the values in IRsensorsValues[0], IRsensorsValues[1], IRsensorsValues[2], IRsensorsValues[3].
Input parameter: none Output parameter: Reads and Prints the values stored at IRsensorsValues[],
void MMkit::waitForStart ()
Description: Continuously checks for the start signal (hand movement close to the left forward distance sensor where a sequence of high, low and high distances are detected)
Input parameter: none Output parameter: none
References readIRSensors().
The documentation for this class was generated from the following files:
MMkit.h
MMkit.cpp